force-app/main/default/objects/Loan_Advance__c/Loan_Advance__c.object-meta.xml
<CustomObject>
    <label>Loan / Advance</label>
    <nameField>
        <displayFormat>LA{0000}</displayFormat>
        <label>Loan / Advance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans / Advances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Advance__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans / Advances</relationshipLabel>
    <relationshipName>Loans_Advances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Advance__c/fields/POS_User__c.field-meta.xml
<CustomField>
    <fullName>POS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>POS User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans / Advances (POS User)</relationshipLabel>
    <relationshipName>Loans_Advances1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Payment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Loan_Advance__c.field-meta.xml
<CustomField>
    <fullName>Loan_Advance__c</fullName>
    <label>Loan / Advance</label>
    <referenceTo>Loan_Advance__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <formula>Loan_Advance__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/POS_User__c.field-meta.xml
<CustomField>
    <fullName>POS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>POS User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments (POS User)</relationshipLabel>
    <relationshipName>Payments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Setting__mdt/Receipt_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Receipt Setting</label>
    <pluralLabel>Receipt Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Receipt_Setting__mdt/fields/Tagline__c.field-meta.xml
<CustomField>
    <fullName>Tagline__c</fullName>
    <label>Tagline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POSPaymentReceiptController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/ 
public without sharing class POSPaymentReceiptController {
    
    
    public class ReceiptData{
        @auraEnabled
        public Payment__c payment;
    }
    
    @auraEnabled
    public static ReceiptData getReceiptData(String recordId){
        system.debug('#' + recordId);
        ReceiptData receipt = new ReceiptData();
        receipt.payment = [SELECT Id, Name, Loan_Advance__r.Name, Contact__r.Name, POS_User__r.Name, Date__c, Amount__c, Loan_Amount__c FROM Payment__c WHERE Id =: recordId];
      
        
        return receipt;        
    }
    
 
    @AuraEnabled
    public static Receipt_Setting__mdt getReceiptSettings() {
        Receipt_Setting__mdt mdt = [SELECT MasterLabel, Address__c, Contact_Number__c, Tagline__c, Title__c FROM Receipt_Setting__mdt WHERE DeveloperName = 'Farm_Grill_Receipt_Settings' LIMIT 1];
        return mdt;
    }
    
}