force-app/main/default/objects/Cash_Drawer_Item__c/Cash_Drawer_Item__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Item</label>
    <nameField>
        <displayFormat>CDI{0000}</displayFormat>
        <label>Cash Drawer Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Cash_Drawer_Session__c.field-meta.xml
<CustomField>
    <fullName>Cash_Drawer_Session__c</fullName>
    <label>Cash Drawer Session</label>
    <referenceTo>Cash_Drawer_Session__c</referenceTo>
    <relationshipName>Cash_Drawer_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <label>Custom</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cash Drawer Items</relationshipLabel>
    <relationshipName>Cash_Drawer_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cash Drawer Items</relationshipLabel>
    <relationshipName>Cash_Drawer_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>(X1000__c * 1000) +
(X500__c * 500) +
(X200__c * 200) +
(X100__c * 100) +
(X50__c * 50) +
(X20__c * 20) +
(X10__c * 10) +
(X5__c * 5) +
(X1__c * 1) +
Custom__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Cash</fullName>
            </value>
            <value>
                <fullName>Ending Count</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Gcash</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Pending Remittance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/Cash_Drawer_Session__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Session</label>
    <nameField>
        <displayFormat>CDS{0000}</displayFormat>
        <label>Cash_Drawer_Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cash Drawer Sessions</relationshipLabel>
    <relationshipName>Cash_Drawer_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cash Drawer Sessions</relationshipLabel>
    <relationshipName>Cash_Drawer_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Expected_Count__c.field-meta.xml
<CustomField>
    <fullName>Expected_Count__c</fullName>
    <formula>(Cash_Float__c +  Total_Additional_Cash__c  +  Total_Sales_Cash__c) -  (Total_Expenses__c +  Total_Withdrawals__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expected Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Number_of_Pending_Remittances__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Pending_Remittances__c</fullName>
    <label>Number of Pending Remittances</label>
    <summaryFilterItems>
        <field>Cash_Drawer_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Pending Remittance</value>
    </summaryFilterItems>
    <summaryForeignKey>Cash_Drawer_Item__c.Cash_Drawer_Session__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reconciling</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
                <isActive>false</isActive>
                <label>Reconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/TECH_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>TECH_Start_Time__c</fullName>
    <formula>IF(
    OR(
        HOUR( Start_Time__c) = 0, 
        HOUR( Start_Time__c) = 12
    ), 
    &apos;12&apos;, 
    TEXT( 
        IF( 
            HOUR( Start_Time__c) &gt; 12, 
            HOUR( Start_Time__c) - 12, 
            HOUR( Start_Time__c) 
        )
    )
) 
&amp; &quot;:&quot; &amp; 
IF (
    MINUTE( Start_Time__c) &lt; 10, 
    &quot;0&quot; + TEXT( MINUTE( Start_Time__c) ), 
    TEXT( MINUTE( Start_Time__c) )
) 
&amp; IF (
    HOUR( Start_Time__c) &lt; 12, 
    &quot; AM&quot;, 
    &quot; PM&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Start_Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Total_Count_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Count_Orders__c</fullName>
    <formula>Number_of_Cash_MOP_Orders__c +  Number_of_GCash_MOP_Orders__c + Number_of_Pending_Remittances__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Count Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Total_Sales_Cash__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Cash__c</fullName>
    <label>Total Sales(Cash)</label>
    <summarizedField>Cash_Drawer_Item__c.Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Cash_Drawer_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Sales</value>
    </summaryFilterItems>
    <summaryForeignKey>Cash_Drawer_Item__c.Cash_Drawer_Session__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Total_Sales_Gcash__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Gcash__c</fullName>
    <label>Total Sales(Gcash)</label>
    <summarizedField>Cash_Drawer_Item__c.Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Cash_Drawer_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Sales Gcash</value>
    </summaryFilterItems>
    <summaryForeignKey>Cash_Drawer_Item__c.Cash_Drawer_Session__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cash_Drawer_Session__c.field-meta.xml
<CustomField>
    <fullName>Cash_Drawer_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cash Drawer Session</label>
    <referenceTo>Cash_Drawer_Session__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cashier_Notes__c.field-meta.xml
<CustomField>
    <fullName>Cashier_Notes__c</fullName>
    <label>Cashier Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Order_DateTime__c</fullName>
    <formula>IF(
    OR(
        VALUE( MID( TEXT( CreatedDate), 12, 2 ) ) = 0,
        VALUE( MID( TEXT( CreatedDate), 12, 2 ) ) = 12
    ),
    &quot;12&quot;,
    TEXT( VALUE( MID( TEXT( CreatedDate), 12, 2 ) )
    -
    IF(
        VALUE( MID( TEXT( CreatedDate ), 12, 2 ) ) &lt; 12,
        0,
        12
    )
    )
)
&amp; &quot;:&quot; &amp;
MID( TEXT( CreatedDate), 15, 2 )
&amp; &quot; &quot; &amp;
IF(
    VALUE( MID( TEXT( CreatedDate), 12, 2 ) ) &lt; 12,
    &quot;AM&quot;,
    &quot;PM&quot;
)</formula>
    <label>Order DateTime</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_Time__c</fullName>
    <label>Order Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Remittance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POSPendingRemittanceController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History 

*/
public without sharing class POSPendingRemittanceController {
    
    @auraEnabled
    public static List<Cash_Drawer_Item__c> getCashDrawerItems(string cashDrawerSessionId){
        List<Cash_Drawer_Item__c> cdss = [SELECT Id, Name, Type__c, Total_Amount__c, Notes__c FROM Cash_Drawer_Item__c WHERE Cash_Drawer_Session__c =: cashDrawerSessionId AND  Type__c = 'Pending Remittance'];
        if(cdss.size() > 0){
            return cdss;
        }else{
            return null;
        } 
        
    }
     
    @auraEnabled
    public static List<Opportunity> getPendingOpportunity(string cashDrawerItemId, string cashierId){
        
        Set<Id> opptySetId = new Set<Id>();
        for (OpportunityContactRole opptyRole : [SELECT Id, OpportunityId FROM OpportunityContactRole 
                                                 WHERE ContactId =: cashierId AND Opportunity.Payment_Status__c = 'Pending Remittance' AND Role = 'Cashier']){
                                                     
                                                     opptySetId.add(opptyRole.OpportunityId);
                                                     
                                                 }
             
        List<Opportunity> oppties = [SELECT Id, Name, Order_DateTime__c, Order_Time__c, Customer__r.Name, Payment_Status__c, StageName, Amount, Cash_Drawer_Session__c FROM Opportunity WHERE 
                                     Id IN: opptySetId AND
                                     Payment_Status__c = 'Pending Remittance'];
        if(oppties.size() > 0){
            return oppties;
        }else{
            return null;
        }
        
    }
    
    
    @auraEnabled
    public static List<Opportunity> updateDeliveryOpportunity(string cashDrawerItemBody, string type){
        system.debug(cashDrawerItemBody);
        Cash_Drawer_Item__c cashDrawerItem = (Cash_Drawer_Item__c) JSON.deserialize(cashDrawerItemBody, Cash_Drawer_Item__c.class);
        Map<Id, PriceBookEntry> pbeMap = new Map<Id, PriceBookEntry>();
        Set<Id> pbEntrySet = new Set<Id>();
        
        if(type == 'Cash'){
            cashDrawerItem.Type__c = 'Sales';
        }else if(type == 'GCash'){
            cashDrawerItem.Type__c = 'Sales Gcash';
        }
        
        Opportunity opp = [SELECT Id, Payment_Status__c, StageName, Cashier_Notes__c, Customer__c, Amount, Cash_Drawer_Session__c FROM Opportunity WHERE Id =: cashDrawerItem.Opportunity__c];
        opp.Payment_Status__c = 'Paid';
        opp.StageName = 'Closed Won - Delivered';
        opp.Cashier_Notes__c = cashDrawerItem.Notes__c;
        opp.Cash_Drawer_Session__c = cashDrawerItem.Cash_Drawer_Session__c;
        update opp;
        
        //Query the Cahier of this opportunity
        OpportunityContactRole cashier = [SELECT Id, OpportunityId, ContactId FROM OpportunityContactRole WHERE OpportunityId =: opp.Id AND Role = 'Cashier' LIMIT 1];
        
        for(OpportunityLineItem opptyLine : [SELECT Id, PricebookEntryId FROM OpportunityLineItem WHERE OpportunityId =: cashDrawerItem.Opportunity__c]){
            pbEntrySet.add(opptyLine.PricebookEntryId);
            
        }
        
        //Loop PriceBookEntry from DB to avoid JS Injection
        for(PriceBookEntry pbe : [SELECT Id, UnitPrice, Product2Id FROM PriceBookEntry WHERE Id IN : pbEntrySet]){
            pbeMap.put(pbe.Id, pbe);
        }
        
        
        //Create Cash Drawer Item
        List<Cash_Drawer_Item__c> cdItems = new List<Cash_Drawer_Item__c>();        
        Cash_Drawer_Item__c cdi = new Cash_Drawer_Item__c();
        cdi.Cash_Drawer_Session__c = cashDrawerItem.Cash_Drawer_Session__c;
        cdi.Type__c = cashDrawerItem.Type__c;
        cdi.Custom__c = opp.Amount;
        cdi.Opportunity__c = opp.Id;
        cdi.Customer__c = opp.Customer__c;
        cdi.Reference_Number__c = cashDrawerItem.Reference_Number__c;
        cdi.Notes__c = cashDrawerItem.Notes__c;
        cdItems.add(cdi);
        
        
        if(cdItems.size() > 0){
            insert cdItems;
        }
        
        List<Opportunity> oppties=  getPendingOpportunity(cashDrawerItem.Cash_Drawer_Session__c, cashier.ContactId);
        
        return oppties;
        
    }
 
    @auraEnabled
    public static List<Cash_Drawer_Item__c> updateCashDrawerItems(string cashDrawerItemId, string cashDrawerItemBody, string type){
        Cash_Drawer_Item__c cashDrawerItem = (Cash_Drawer_Item__c) JSON.deserialize(cashDrawerItemBody, Cash_Drawer_Item__c.class);
        Cash_Drawer_Item__c cdi = [SELECT Id, Cash_Drawer_Session__c, Notes__c, Reference_Number__c, Type__c, Custom__c FROM Cash_Drawer_Item__c WHERE Id=: cashDrawerItemId];
    
        if(type == 'Cash'){
            cdi.Type__c = 'Sales';
        }else if(type == 'GCash'){
            cdi.Type__c = 'Sales Gcash';
        }
        
        cdi.Notes__c = cashDrawerItem.Notes__c;
        cdi.Custom__c = cashDrawerItem.Custom__c;
        cdi.Reference_Number__c = cashDrawerItem.Reference_Number__c;
        update cdi;
        
        
        List<Cash_Drawer_Item__c> cdIs = getCashDrawerItems(cdi.Opportunity__c);
       
        if(cdIs.size() > 0){
            return cdIs;
        }else{
            return null;
        }
      
        
    }
    
    @auraEnabled
    public static Cash_Drawer_Session__c getCashDrawer(String employeeId, String accountId){
        
        Cash_Drawer_Session__c cd = new Cash_Drawer_Session__c();
        List<Cash_Drawer_Session__c> activeCashDrawer = [SELECT Id, Status__c, Total_Sales_Cash__c, Total_Count_Orders__c,Total_Sales_Gcash__c, TECH_Start_Time__c, Start_Date__c,
                                                         Expected_Count__c, End_Date__c, Number_of_Pending_Remittances__c	
                                                         FROM Cash_Drawer_Session__c WHERE Contact__c =: employeeId AND Account__c =: accountId ORDER BY CreatedDate DESC LIMIT 1];
        if(activeCashDrawer.size() > 0){
            cd = activeCashDrawer[0];
            
        }else{
            return null;
        }
        
        //return null if there is no account found
        return cd;
    }
    
 
}