force-app/main/default/objects/Cash_Drawer_Item__c/Cash_Drawer_Item__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Item</label>
    <nameField>
        <displayFormat>CDI{0000}</displayFormat>
        <label>Cash Drawer Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Cash_Drawer_Session__c.field-meta.xml
<CustomField>
    <fullName>Cash_Drawer_Session__c</fullName>
    <label>Cash Drawer Session</label>
    <referenceTo>Cash_Drawer_Session__c</referenceTo>
    <relationshipName>Cash_Drawer_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Cash</fullName>
            </value>
            <value>
                <fullName>Ending Count</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Gcash</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Pending Remittance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/Cash_Drawer_Session__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Session</label>
    <nameField>
        <displayFormat>CDS{0000}</displayFormat>
        <label>Cash_Drawer_Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cash Drawer Sessions</relationshipLabel>
    <relationshipName>Cash_Drawer_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reconciling</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
                <isActive>false</isActive>
                <label>Reconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POSCashDrawerNewItemController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/
public without sharing class POSCashDrawerNewItemController {

    @auraEnabled
    public static Cash_Drawer_Item__c createCashDrawerItem(String cashDrawerId, String cashDrawerItem, String type){
        system.debug(cashDrawerItem);
        system.debug(cashDrawerId);
        Cash_Drawer_Item__c cdi = (Cash_Drawer_Item__c)  JSON.deserialize(cashDrawerItem, Cash_Drawer_Item__c.class);
        cdi.Type__c = type;
        cdi.Cash_Drawer_Session__c = cashDrawerId;
        system.debug(cdi);
        insert cdi;
        
        if(type == 'Ending Count'){
            Cash_Drawer_Session__c pos = POSMainController.endCashDrawer(cashDrawerId);
        }
        //return null if there is no account found
        return cdi;
    }
    
     
    @auraEnabled
    public static Cash_Drawer_Session__c endCashDrawer(String cashDrawerId){
        system.debug('cashDrawerId: ' + cashDrawerId);
        Cash_Drawer_Session__c cd = [SELECT Id, Contact__c, End_Date__c, End_Time__c FROM Cash_Drawer_Session__c WHERE Id =: cashDrawerId];
        
        DateTime gmtNow = System.now();
        Time localTime = gmtNow.time();
        
        cd.End_Date__c = system.today();
        cd.End_Time__c = localTime;
        cd.Status__c = 'Reconciling';
        update cd;
        
        //cd = getCashDrawer(cd.Contact__c);
        
        //return null if there is no account found
        return cd;
    }
    
}