force-app/main/default/objects/Cash_Drawer_Item__c/Cash_Drawer_Item__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Item</label>
    <nameField>
        <displayFormat>CDI{0000}</displayFormat>
        <label>Cash Drawer Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Cash_Drawer_Session__c.field-meta.xml
<CustomField>
    <fullName>Cash_Drawer_Session__c</fullName>
    <label>Cash Drawer Session</label>
    <referenceTo>Cash_Drawer_Session__c</referenceTo>
    <relationshipName>Cash_Drawer_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Custom__c.field-meta.xml
<CustomField>
    <fullName>Custom__c</fullName>
    <label>Custom</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Cash Drawer Items</relationshipLabel>
    <relationshipName>Cash_Drawer_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Queue_Number__c.field-meta.xml
<CustomField>
    <fullName>Queue_Number__c</fullName>
    <formula>Opportunity__r.Queue_Number__c</formula>
    <label>Queue Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>(X1000__c * 1000) +
(X500__c * 500) +
(X200__c * 200) +
(X100__c * 100) +
(X50__c * 50) +
(X20__c * 20) +
(X10__c * 10) +
(X5__c * 5) +
(X1__c * 1) +
Custom__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Cash</fullName>
            </value>
            <value>
                <fullName>Ending Count</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Float</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Gcash</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Pending Remittance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X1000__c.field-meta.xml
<CustomField>
    <fullName>X1000__c</fullName>
    <label>1000</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X100__c.field-meta.xml
<CustomField>
    <fullName>X100__c</fullName>
    <label>100</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X10__c.field-meta.xml
<CustomField>
    <fullName>X10__c</fullName>
    <label>10</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X1__c.field-meta.xml
<CustomField>
    <fullName>X1__c</fullName>
    <label>1</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X200__c.field-meta.xml
<CustomField>
    <fullName>X200__c</fullName>
    <label>200</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X20__c.field-meta.xml
<CustomField>
    <fullName>X20__c</fullName>
    <label>20</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X500__c.field-meta.xml
<CustomField>
    <fullName>X500__c</fullName>
    <label>500</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X50__c.field-meta.xml
<CustomField>
    <fullName>X50__c</fullName>
    <label>50</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Item__c/fields/X5__c.field-meta.xml
<CustomField>
    <fullName>X5__c</fullName>
    <label>5</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/Cash_Drawer_Session__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Session</label>
    <nameField>
        <displayFormat>CDS{0000}</displayFormat>
        <label>Cash_Drawer_Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Cash_Drawer_Session__c.field-meta.xml
<CustomField>
    <fullName>Cash_Drawer_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cash Drawer Session</label>
    <referenceTo>Cash_Drawer_Session__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cash_Tendered__c.field-meta.xml
<CustomField>
    <fullName>Cash_Tendered__c</fullName>
    <label>Cash Tendered</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <formula>IF( Cash_Tendered__c  != 0 , Cash_Tendered__c - Amount, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Queue_Number__c.field-meta.xml
<CustomField>
    <fullName>Queue_Number__c</fullName>
    <label>Queue Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Setting__mdt/Receipt_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Receipt Setting</label>
    <pluralLabel>Receipt Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Receipt_Setting__mdt/fields/Tagline__c.field-meta.xml
<CustomField>
    <fullName>Tagline__c</fullName>
    <label>Tagline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POSReceiptController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/ 
public without sharing class POSReceiptController {
    
    
    public class ReceiptData{
        @auraEnabled
        public Opportunity oppty;
        @auraEnabled
        public List<OpportunityLineItem> opptyLines;
    }
    
    @auraEnabled
    public static ReceiptData getReceiptData(String recordId){
        system.debug('#' + recordId);
        ReceiptData receipt = new ReceiptData();
        receipt.oppty = [SELECT Id, Queue_Number__c, Amount, Cash_Tendered__c, Change__c FROM Opportunity WHERE Id =: recordId];
        receipt.opptyLines = [SELECT Id, Product2.Name, Quantity, TotalPrice FROM OpportunityLineItem WHERE OpportunityId =: recordId];
        
        return receipt;        
    }
    
    @auraEnabled
    public static Cash_Drawer_Item__c getCashDrawerItem(String recordId){
        
        Cash_Drawer_Item__c cdi = [SELECT Id, Cash_Drawer_Session__r.Name, Custom__c, Notes__c, Opportunity_Product__c, Type__c, 
                                   X1000__c, X100__c, X10__c, X1__c, X200__c, X20__c, X500__c, X50__c, X5__c, 
                                   Total_Amount__c FROM Cash_Drawer_Item__c WHERE Id =: recordId];
        
        return cdi;        
    }
    
    
    
    @AuraEnabled
    public static Receipt_Setting__mdt getReceiptSettings() {
        Receipt_Setting__mdt mdt = [SELECT MasterLabel, Address__c, Contact_Number__c, Tagline__c, Title__c FROM Receipt_Setting__mdt WHERE DeveloperName = 'Farm_Grill_Receipt_Settings' LIMIT 1];
        return mdt;
    }
    
}