force-app/main/default/objects/Lead_Line_Item__c/Lead_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Lead Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lead Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Line_Item__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Special_Notes__c.field-meta.xml
<CustomField>
    <fullName>Special_Notes__c</fullName>
    <label>Special Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>TECH_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_MainProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_PricebookEntry__c.field-meta.xml
<CustomField>
    <fullName>TECH_PricebookEntry__c</fullName>
    <label>TECH_PricebookEntry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Resto_Site_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Resto_Site_Display_Name__c</fullName>
    <label>Resto Site Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/Product_Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Product Stock Level</label>
    <nameField>
        <displayFormat>SLP{0000}</displayFormat>
        <label>Stock Level Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <formula>Stock_Level__r.Available_to_Sell__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available to Sell</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <referenceTo>Stock_Level__c</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Units</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Stock Level</label>
    <nameField>
        <displayFormat>SL{0000}</displayFormat>
        <label>Stock Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available to Sell</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Change_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Change_Quantity__c</fullName>
    <label>Change Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock Levels</relationshipLabel>
    <relationshipName>Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FGUtilities.cls
public class FGUtilities {
    
    @AuraEnabled
    public static List<Stock_Level__c> checkProductsStockList(Lead lead){
        
        Map<String, Lead_Line_Item__c> leadItemMap = new Map<String, Lead_Line_Item__c>();
        for(Lead_Line_Item__c li : [SELECT Id, Product__c, TECH_MainProduct__c, Product__r.Name, Product__r.Resto_Site_Display_Name__c, Quantity__c, Total_Price__c, Unit_Price__c, Special_Notes__c, TECH_PricebookEntry__c
                                    FROM Lead_Line_Item__c WHERE Lead__c =: lead.Id AND Product__r.Track_Inventory__c = TRUE]){
                                        
                                        
                                        leadItemMap.put(li.Product__c, li);
                                        
                                        
                                        
                                    }
        
        Map<Id, Stock_Level__c> currentStockLevelMap = new Map<Id, Stock_Level__c>(); 
        for(Product_Stock_Level__c psl : [SELECT Id, Product__c, Stock_Level__c, Available_to_Sell__c, Units__c FROM Product_Stock_Level__c WHERE Product__c IN : leadItemMap.keySet()]){
            
            
            if(leadItemMap.containsKey(psl.Product__c)){
                
                if(currentStockLevelMap.containsKey(psl.Stock_Level__c)){
                    //Current quantity + the new units sold
                    currentStockLevelMap.get(psl.Stock_Level__c).Change_Quantity__c = currentStockLevelMap.get(psl.Stock_Level__c).Change_Quantity__c + (leadItemMap.get(psl.Product__c).Quantity__c * psl.Units__c);
                }else{
                    
                    Stock_Level__c sl = new Stock_Level__c();
                    sl.Id = psl.Stock_Level__c;
                    sl.Change_Quantity__c = leadItemMap.get(psl.Product__c).Quantity__c * psl.Units__c;
                    currentStockLevelMap.put(psl.Stock_Level__c, sl);
                }
                
                
            }
            
            
            
            
        }
        
        
        //Make the change quantity negative value
        for(String slKey : currentStockLevelMap.KeySet()){
            
            if(currentStockLevelMap.containsKey(slKey)){
                currentStockLevelMap.get(slKey).Change_Quantity__c = -(currentStockLevelMap.get(slKey).Change_Quantity__c);
            }
            
        } 
        
        
        for(Product_Stock_Level__c psl : [SELECT Id, Product__c, Stock_Level__c, Stock_Level__r.Name, Available_to_Sell__c, Units__c FROM Product_Stock_Level__c 
                                          WHERE Product__c IN : leadItemMap.keySet()]){
                                              
                                              if(currentStockLevelMap.containsKey(psl.Stock_Level__c)){
                                                  //Change Quantity is in NEgative so that the stock gets minus because of flow
                                                  Decimal stockCount = psl.Available_to_Sell__c + currentStockLevelMap.get(psl.Stock_Level__c).Change_Quantity__c;
                                                  if(stockCount < 0){
                                                      
                                                      try {
                                                          Map<String, String> errorMap = new Map<String, String>{
                                                              'code' => '400',
                                                                  'message' => 'ERROR: ' + psl.Stock_Level__r.Name + ' is out of stock or not enough. Please remove it from your Cart. \n  Available stock is ' + psl.Available_to_Sell__c ,
                                                                  'severity' => 'High'
                                                                  };
                                                                      throw new AuraHandledException(JSON.serialize(errorMap));
                                                          
                                                      } catch (Exception e) {
                                                          // If it's already an AuraHandledException, rethrow it
                                                          if(e instanceof AuraHandledException) throw e;
                                                          // Otherwise, wrap the system error
                                                          throw new AuraHandledException('System Error: ' + e.getMessage());
                                                      }
                                                      
                                                  }
                                                  
                                              }
                                              
                                          }
        
        if(currentStockLevelMap.size() > 0){
            
        }
        
        return currentStockLevelMap.values();
    }
    
}