force-app/main/default/objects/Lead_Line_Item__c/Lead_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Lead Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lead Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Line_Item__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>TECH_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_MainProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Resto_Site_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Resto_Site_Display_Name__c</fullName>
    <label>Resto Site Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FGCartController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/  
public without sharing class FGCartController {
    
    @AuraEnabled
    public static List<Lead_Line_Item__c> getLeadItems(String leadId){
        
        List<Lead_Line_Item__c> lineItems = [SELECT Id, Product__c, Product__r.Name,Product__r.Product_Image_Url__c, Quantity__c, Total_Price__c, Product__r.Resto_Site_Display_Name__c 
                                             FROM Lead_Line_Item__c WHERE Lead__c =: leadId ORDER BY TECH_MainProduct__c DESC];
        if(lineItems.size() > 0){
           return lineItems;  
        }else{
            return null;
        }
        
    }
    
    
    @AuraEnabled
    public static Lead_Line_Item__c updateLeadItem(String leadItemId, string method){
        
        Lead_Line_Item__c lineItem = [SELECT Id, Product__c, Product__r.Name,Product__r.Product_Image_Url__c, Quantity__c, Total_Price__c, Product__r.Resto_Site_Display_Name__c 
                                             FROM Lead_Line_Item__c WHERE Id =: leadItemId];
        
        if(method == 'ADD'){
            lineItem.Quantity__c = lineItem.Quantity__c + 1;
        }else{
            lineItem.Quantity__c = lineItem.Quantity__c - 1;
        }
         
        update lineItem;
        
        return lineItem; 
    }
    
      @AuraEnabled
    public static void deleteItem(String leadItemId){
        
        Lead_Line_Item__c lineItem = [SELECT Id FROM Lead_Line_Item__c WHERE Id =: leadItemId];
        
        delete lineItem;
        
    }

    
}