force-app/main/default/objects/Lead_Line_Item__c/Lead_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Lead Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lead Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Line_Item__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Resto_Site_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Resto_Site_Display_Name__c</fullName>
    <label>Resto Site Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Family__c.field-meta.xml
<CustomField>
    <fullName>Sub_Family__c</fullName>
    <label>Sub Family</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Solo</fullName>
            </value>
            <value>
                <fullName>With Rice</fullName>
            </value>
            <value>
                <fullName>Unli Rice</fullName>
            </value>
            <value>
                <fullName>Platter</fullName>
            </value>
            <value>
                <fullName>Rice Meal</fullName>
            </value>
            <value>
                <fullName>Paa</fullName>
            </value>
            <value>
                <fullName>Pecho</fullName>
            </value>
            <value>
                <fullName>120G w/ Rice</fullName>
            </value>
            <value>
                <fullName>500G</fullName>
            </value>
            <value>
                <fullName>1KG</fullName>
            </value>
            <value>
                <fullName>Swakto</fullName>
            </value>
            <value>
                <fullName>Mismo</fullName>
            </value>
            <value>
                <fullName>1.5L</fullName>
            </value>
            <value>
                <fullName>350ML</fullName>
            </value>
            <value>
                <fullName>500ML</fullName>
            </value>
            <value>
                <fullName>1L</fullName>
            </value>
            <value>
                <fullName>Dolores Poblacion</fullName>
            </value>
            <value>
                <fullName>Dapdap</fullName>
            </value>
            <value>
                <fullName>Lunang</fullName>
            </value>
            <value>
                <fullName>Salak</fullName>
            </value>
            <value>
                <fullName>Malaintos</fullName>
            </value>
            <value>
                <fullName>Malobago</fullName>
            </value>
            <value>
                <fullName>Pecho - Unli</fullName>
            </value>
            <value>
                <fullName>Paa - Unli</fullName>
            </value>
            <value>
                <fullName>Free</fullName>
            </value>
            <value>
                <fullName>Extra Rice</fullName>
            </value>
            <value>
                <fullName>Chicken Oil</fullName>
            </value>
            <value>
                <fullName>Spice Vinegar</fullName>
            </value>
            <value>
                <fullName>230ML</fullName>
            </value>
            <value>
                <fullName>220ML</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Catalog__c/Product_Catalog__c.object-meta.xml
<CustomObject>
    <label>Product Catalog</label>
    <nameField>
        <label>Product Catalog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalog_Item__c/Product_Catalog_Item__c.object-meta.xml
<CustomObject>
    <label>Product Catalog Item</label>
    <nameField>
        <displayFormat>PCI{000000}</displayFormat>
        <label>Product Catalog Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alacarte</fullName>
            </value>
            <value>
                <fullName>Meal - with Rice</fullName>
            </value>
            <value>
                <fullName>Meal - Unli Rice</fullName>
            </value>
            <value>
                <fullName>Meal - with Rice &amp; Drink</fullName>
            </value>
            <value>
                <fullName>Bilao / Family Bundle</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Veggies</fullName>
            </value>
            <value>
                <fullName>Inasal</fullName>
            </value>
            <value>
                <fullName>BBQ/Grill/Lechon</fullName>
            </value>
            <value>
                <fullName>Add ons</fullName>
            </value>
            <value>
                <fullName>Dessert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Popular__c.field-meta.xml
<CustomField>
    <fullName>Popular__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Popular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Product_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalog__c</fullName>
    <label>Product Catalog</label>
    <referenceTo>Product_Catalog__c</referenceTo>
    <relationshipName>Product_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Row_Priority__c.field-meta.xml
<CustomField>
    <fullName>Row_Priority__c</fullName>
    <label>Row Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/TECH_PriceBookEntryId__c.field-meta.xml
<CustomField>
    <fullName>TECH_PriceBookEntryId__c</fullName>
    <label>TECH_PriceBookEntryId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/TECH_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>TECH_Unit_Price__c</fullName>
    <label>TECH_Unit_Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Resto_Site_Setting__mdt/Resto_Site_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Resto Site Setting</label>
    <pluralLabel>Resto Site Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Resto_Site_Setting__mdt/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <label>Catalog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FGContainerController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/  
public without sharing class FGContainerController {
    
    @auraEnabled
    public static Resto_Site_Setting__mdt getSiteSettings(String settingName){
        Resto_Site_Setting__mdt posSettings = new Resto_Site_Setting__mdt();
        if(settingName != ''){
            return Resto_Site_Setting__mdt.getInstance(settingName);
        }else{
            return null;
        }
        
    }
    
    
    @AuraEnabled
    public static Map<String, List<Product_Catalog_Item__c>> getProducts(){
        
        Resto_Site_Setting__mdt fgSetting = getSiteSettings('Farm_Grill_Settings');
        
        Map<String, List<Product_Catalog_Item__c>> prodMap = new Map<String, List<Product_Catalog_Item__c>>();
        List<Product_Catalog_Item__c> products = [SELECT Id, Category__c, Product__r.Sub_Family__c, Popular__c, Product__r.Display_Name__c, Product__r.Resto_Site_Display_Name__c, Product__r.Description,
                                                  Product__c, Product_Group__c, Product_Group__r.Name, Product_Group__r.Product_Image_Url__c, Product__r.ProductCode, Product__r.Name, 
                                                  Product__r.Product_Image_Url__c 
                                                  FROM Product_Catalog_Item__c 
                                                  WHERE Product_Catalog__r.Active__c = TRUE AND Product_Catalog__r.Name =: fgSetting.Catalog__c AND Category__c != 'Delivery'  ORDER BY Priority__c ASC, Row_Priority__c ASC];
        
        Map<String, PriceBookEntry> sPriceBookEntryMap = new Map<String, PriceBookEntry>();
        for(PriceBookEntry pb : [SELECT Id, Product2Id, UnitPrice FROM PriceBookEntry WHERE PriceBook2.Name = 'Standard Price Book']){
            sPriceBookEntryMap.put(pb.Product2Id, pb);
        }
        
        for(Product_Catalog_Item__c pc : products){
        
            
            if(sPriceBookEntryMap.containsKey(pc.Product__c)){
                pc.TECH_PriceBookEntryId__c = sPriceBookEntryMap.get(pc.Product__c).Id;
                pc.TECH_Unit_Price__c = sPriceBookEntryMap.get(pc.Product__c).UnitPrice;
            }
            if(prodMap.containsKey(pc.Category__c)){
                prodMap.get(pc.Category__c).add(pc);
            }else{
                prodMap.put(pc.Category__c, new List<Product_Catalog_Item__c>{pc});
            }
            
          
            
        }
        
        return prodMap;
    }
    
    
    @AuraEnabled
    public static Map<String, Decimal> getCart(String leadId) {
        AggregateResult[] groupedResults = [SELECT SUM(Quantity__c) sumQty, 
                                            SUM(Total_Price__c) sumTotalPrice 
                                            FROM Lead_Line_Item__c WHERE Lead__c =: leadId];
        
        Map<String, Decimal> resultMap = new Map<String, Decimal>();
        if (groupedResults.size() > 0) {
            
            if(groupedResults[0].get('sumQty') != null){
                resultMap.put('totalQty', (Decimal)groupedResults[0].get('sumQty'));
                resultMap.put('totalPrice', (Decimal)groupedResults[0].get('sumTotalPrice'));
            }else{
                resultMap.put('totalQty',0);
                resultMap.put('totalPrice', 0);
            }
            
        }
        return resultMap;
    }
    
    
    

}