force-app/main/default/objects/Cash_Drawer_Session__c/Cash_Drawer_Session__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Session</label>
    <nameField>
        <displayFormat>CDS{0000}</displayFormat>
        <label>Cash_Drawer_Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Cash_Drawer_Session__c.field-meta.xml
<CustomField>
    <fullName>Cash_Drawer_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cash Drawer Session</label>
    <referenceTo>Cash_Drawer_Session__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Order_DateTime__c</fullName>
    <formula>IF(
    OR(
        VALUE( MID( TEXT( CreatedDate), 12, 2 ) ) = 0,
        VALUE( MID( TEXT( CreatedDate), 12, 2 ) ) = 12
    ),
    &quot;12&quot;,
    TEXT( VALUE( MID( TEXT( CreatedDate), 12, 2 ) )
    -
    IF(
        VALUE( MID( TEXT( CreatedDate ), 12, 2 ) ) &lt; 12,
        0,
        12
    )
    )
)
&amp; &quot;:&quot; &amp;
MID( TEXT( CreatedDate), 15, 2 )
&amp; &quot; &quot; &amp;
IF(
    VALUE( MID( TEXT( CreatedDate), 12, 2 ) ) &lt; 12,
    &quot;AM&quot;,
    &quot;PM&quot;
)</formula>
    <label>Order DateTime</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_Time__c</fullName>
    <label>Order Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Remittance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POSOnlineOrdersController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History 

*/
public without sharing class POSOnlineOrdersController {
    
    
    
    @auraEnabled
    public static List<Opportunity> getPendingOpportunity(string cashDrawerItemId, string cashierId){
        
        List<Opportunity> oppties = [SELECT Id, Name, Order_DateTime__c, CreatedDate, Order_Time__c, Customer__r.Name, Payment_Status__c, StageName, Amount, Cash_Drawer_Session__c FROM Opportunity WHERE 
                                     StageName = 'Pending Review'];
        if(oppties.size() > 0){
            return oppties;
        }else{
            return null;
        }
        
    }
    
    
    
}