force-app/main/default/objects/Cash_Drawer_Session__c/Cash_Drawer_Session__c.object-meta.xml
<CustomObject>
    <label>Cash Drawer Session</label>
    <nameField>
        <displayFormat>CDS{0000}</displayFormat>
        <label>Cash_Drawer_Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Drawer Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cash Drawer Sessions</relationshipLabel>
    <relationshipName>Cash_Drawer_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cash Drawer Sessions</relationshipLabel>
    <relationshipName>Cash_Drawer_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Difference__c.field-meta.xml
<CustomField>
    <fullName>Difference__c</fullName>
    <formula>Ending_Count__c - Expected_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Difference</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Ending_Count__c.field-meta.xml
<CustomField>
    <fullName>Ending_Count__c</fullName>
    <label>Ending Count</label>
    <summarizedField>Cash_Drawer_Item__c.Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Cash_Drawer_Item__c.Type__c</field>
        <operation>equals</operation>
        <value>Ending Count</value>
    </summaryFilterItems>
    <summaryForeignKey>Cash_Drawer_Item__c.Cash_Drawer_Session__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Expected_Count__c.field-meta.xml
<CustomField>
    <fullName>Expected_Count__c</fullName>
    <formula>(Cash_Float__c +  Total_Additional_Cash__c  +  Total_Sales_Cash__c) -  (Total_Expenses__c +  Total_Withdrawals__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expected Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Drawer_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reconciling</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
                <isActive>false</isActive>
                <label>Reconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Manage_Cash_Drawers__c.field-meta.xml
<CustomField>
    <fullName>Manage_Cash_Drawers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manage Cash Drawers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Resigned</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POSCashDrawersListController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History 

*/
public without sharing class POSCashDrawersListController {
    
     
    @auraEnabled
    public static List<Cash_Drawer_Session__c> getCashDrawers(String accountId){
        
        Cash_Drawer_Session__c cd = new Cash_Drawer_Session__c();
        List<Cash_Drawer_Session__c> activeCashDrawers = [SELECT Id, Name, Status__c, Account__c, Start_Date__c, Contact__c, Contact__r.Name, Contact__r.Manage_Cash_Drawers__c,
                                                         Expected_Count__c, Ending_Count__c, Difference__c	
                                                         FROM Cash_Drawer_Session__c WHERE Account__c =: accountId AND Status__c != 'Closed' 
                                                          AND Contact__r.FirstName != 'Chad' 
                                                          AND Contact__r.FirstName != 'Charina' ORDER BY CreatedDate];
      
        
        //return null if there is no account found
        return activeCashDrawers;
    }
    
    @auraEnabled
    public static Contact getContact(String contactId){
        
        Contact con = [SELECT Id, Name, Manage_Cash_Drawers__c FROM Contact WHERE Id =: contactId];
      
        
        //return null if there is no account found
        return con;
    }
    
    
    @auraEnabled
    public static List<Cash_Drawer_Session__c> updateCashDrawer(String cashdrawerJSON, String status, String note){
        
        Cash_Drawer_Session__c cd = (Cash_Drawer_Session__c) JSON.deserialize(cashdrawerJSON, Cash_Drawer_Session__c.class);
        system.debug(cd);
        cd.Status__c = status;
        cd.Notes__c = note;
        update cd;
        
        return getCashDrawers(cd.Account__c);
    }
    
    

}