force-app/main/default/objects/Product2/fields/Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/Product_Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Product Stock Level</label>
    <nameField>
        <displayFormat>SLP{0000}</displayFormat>
        <label>Stock Level Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <referenceTo>Stock_Level__c</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Stock Level</label>
    <nameField>
        <displayFormat>SL{0000}</displayFormat>
        <label>Stock Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Level__c/fields/Change_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Change_Quantity__c</fullName>
    <label>Change Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock Levels</relationshipLabel>
    <relationshipName>Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/POS_VoidOrderInvocable.cls
/*
* @Author: Chad Lazarra
* @Date: 2-Feb-26
* @Desc:
*/
public without sharing class POS_VoidOrderInvocable {
    
    @InvocableMethod(label='Void Order' description='Accepts a record ID and performs custom logic' category='Opportunity')
    public static void voidOrder(List<Id> recordIds) {
        List<String> results = new List<String>();
        
  
        if (recordIds == null || recordIds.isEmpty()) {
            return;
        }
        
    
        Opportunity oppty = [SELECT Id, Name FROM Opportunity WHERE Id IN :recordIds LIMIT 1];
        Map<Id, Decimal> prodQuantityMap = new Map<Id, Decimal>();
   
        for (OpportunityLineItem opptyLine : [SELECT Id, Product2Id, Quantity FROM OpportunityLineItem WHERE OpportunityId =: oppty.Id AND Product2.Track_Inventory__c = true]) {
            if(prodQuantityMap.containsKey(opptyLine.Product2Id)){
                prodQuantityMap.put(opptyLine.Product2Id,  prodQuantityMap.get(opptyLine.Product2Id) + opptyLine.Quantity);
            }else{
                prodQuantityMap.put(opptyLine.Product2Id, opptyLine.Quantity);
            }
            
        }
        system.debug('prodQuantityMap: ' + prodQuantityMap);
        if(prodQuantityMap.size() > 0){
            List<Stock_Level__c> stockLevelToUpdate = new List<Stock_Level__c>();
            Map<Id, Decimal> stockLevelMap = new Map<Id, Decimal>();
            Map<Id, Id> prodStockLvlMap = new Map<Id, Id>();
            
            for(Product_Stock_Level__c psl : [SELECT Id, Stock_Level__c, Product__c FROM Product_Stock_Level__c WHERE Product__c IN : prodQuantityMap.keySet()]){
                
                prodStockLvlMap.put(psl.Product__c, psl.Stock_Level__c);
                
            }
            
            for(Product_Stock_Level__c psl : [SELECT Id, Stock_Level__c, Product__c FROM Product_Stock_Level__c WHERE Product__c IN : prodQuantityMap.keySet()]){
                 
                if(prodQuantityMap.containsKey(psl.Product__c)){
                    
                    if(stockLevelMap.containsKey(psl.Stock_Level__c)){
                        stockLevelMap.put(psl.Stock_Level__c, stockLevelMap.get(psl.Stock_Level__c) + prodQuantityMap.get(psl.Product__c));
                    }else{
                        stockLevelMap.put(psl.Stock_Level__c, prodQuantityMap.get(psl.Product__c));
                    }
                    
                    /*
                    if(stockLevelMap.containsKey(psl.Stock_Level__c)){
                        stockLevelMap.put(psl.Stock_Level__c, stockLevelMap.get(psl.Stock_Level__c) + prodQuantityMap.get(psl.Product__c));
                        
                    }else{
                        stockLevelMap.put(psl.Stock_Level__c, prodQuantityMap.get(psl.Product__c));
                        
                    }
                    
                    Stock_Level__c sl = new Stock_Level__c();
                    sl.Id = psl.Stock_Level__c;
                    sl.Change_Quantity__c = prodQuantityMap.get(psl.Product__c);
                    stockLevelToUpdate.add(sl);
                    
                    */
                }
                
            }
            
            system.debug(stockLevelMap);
            
            
            //Loop Stock Level Map for Update
            for(ID slId : stockLevelMap.keySet()){
                Stock_Level__c sl = new Stock_Level__c();
                sl.Id = slId;
                sl.Change_Quantity__c = stockLevelMap.get(slId);
                stockLevelToUpdate.add(sl);
                
            }
            
            if(stockLevelToUpdate.size() > 0){
                update stockLevelToUpdate;
            }
            
        }
        
        return;
    }
}