force-app/main/default/objects/Product2/fields/Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/Stock_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Stock Adjustment</label>
    <nameField>
        <displayFormat>SA{0000}</displayFormat>
        <label>Stock Adjustment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Adjustment__c/fields/POS_User__c.field-meta.xml
<CustomField>
    <fullName>POS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>POS User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stock Adjustments</relationshipLabel>
    <relationshipName>Stock_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Level</label>
    <referenceTo>Stock_Level__c</referenceTo>
    <relationshipLabel>Stock Adjustments</relationshipLabel>
    <relationshipName>Stock_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Inventory</fullName>
            </value>
            <value>
                <fullName>Stock Take Adjustment</fullName>
            </value>
            <value>
                <fullName>Transfer Created</fullName>
            </value>
            <value>
                <fullName>Transfer Received</fullName>
            </value>
            <value>
                <fullName>Received From Supplier</fullName>
            </value>
            <value>
                <fullName>Returned To Supplier</fullName>
            </value>
            <value>
                <fullName>Inventory Added</fullName>
            </value>
            <value>
                <fullName>Inventory Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Level__c/Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Stock Level</label>
    <nameField>
        <displayFormat>SL{0000}</displayFormat>
        <label>Stock Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available to Sell</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Count_on_Hand__c.field-meta.xml
<CustomField>
    <fullName>Count_on_Hand__c</fullName>
    <label>Count on Hand</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock Levels</relationshipLabel>
    <relationshipName>Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/POSProductsController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date: Jan 2, 2026
@Desc:
@History 

*/
public without sharing class POSProductsController {
    
    @auraEnabled
    public static List<Stock_Level__c> getProductStocks(){
         
        List<Stock_Level__c> prodStocks = [SELECT Id, Name, Available_to_Sell__c, Count_on_Hand__c, Product__r.Name, Product__r.Family FROM Stock_Level__c 
                                           WHERE Product__r.Track_Inventory__c = TRUE ORDER BY Product__r.Name];
        
        
        //return null if there is no account found
        return prodStocks;
    }
    
    
    @auraEnabled
    public static List<Stock_Level__c> updateStockLevel(string stockLevelBody, string contactId, Decimal amount){
        system.debug(stockLevelBody);
        Stock_Level__c stockLevel = (Stock_Level__c) JSON.deserialize(stockLevelBody, Stock_Level__c.class);
        
        Stock_Level__c stockToUpdate = [SELECT Id, Name, Available_to_Sell__c, Count_on_Hand__c FROM Stock_Level__c 
                                        WHERE Id =: stockLevel.Id];
        
        stockToUpdate.Available_to_Sell__c = stockToUpdate.Available_to_Sell__c + amount;
        stockToUpdate.Count_on_Hand__c = stockToUpdate.Count_on_Hand__c + amount;
        update stockToUpdate;
        
        Stock_Adjustment__c stockAdjustment = new Stock_Adjustment__c();
        stockAdjustment.Type__c = 'Inventory Added';
        stockAdjustment.POS_User__c = contactId;
        stockAdjustment.Amount__c = amount;
        stockAdjustment.Stock_Level__c = stockLevel.Id;
        
        insert stockAdjustment;
        
        List<Stock_Level__c> stocks =  getProductStocks();
        
        return stocks;
        
    }
    
    
}