force-app/main/default/objects/Account/fields/Complete_Address__c.field-meta.xml
<CustomField>
    <fullName>Complete_Address__c</fullName>
    <label>Complete Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Barangay_Sitio__c.field-meta.xml
<CustomField>
    <fullName>Barangay_Sitio__c</fullName>
    <label>Barangay / Sitio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Barangays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Complete_Address__c.field-meta.xml
<CustomField>
    <fullName>Complete_Address__c</fullName>
    <label>Complete Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Municipality_City__c.field-meta.xml
<CustomField>
    <fullName>Municipality_City__c</fullName>
    <label>Municipality / City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Municipalities_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Delivery_Fee_Setting__mdt/Delivery_Fee_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Delivery Fee Setting</label>
    <pluralLabel>Delivery Fee Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Delivery_Fee_Setting__mdt/fields/Barangay_Sitio__c.field-meta.xml
<CustomField>
    <fullName>Barangay_Sitio__c</fullName>
    <label>Barangay / Sitio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barangay 1</fullName>
                <default>true</default>
                <label>Barangay 1</label>
            </value>
            <value>
                <fullName>Barangay 2</fullName>
            </value>
            <value>
                <fullName>Barangay 2 - Salak</fullName>
            </value>
            <value>
                <fullName>Barangay 3</fullName>
            </value>
            <value>
                <fullName>Barangay 4</fullName>
            </value>
            <value>
                <fullName>Barangay 5</fullName>
            </value>
            <value>
                <fullName>Barangay 6</fullName>
            </value>
            <value>
                <fullName>Barangay 7</fullName>
            </value>
            <value>
                <fullName>Barangay 8</fullName>
            </value>
            <value>
                <fullName>Barangay 9</fullName>
            </value>
            <value>
                <fullName>Barangay 10</fullName>
            </value>
            <value>
                <fullName>Barangay 11</fullName>
            </value>
            <value>
                <fullName>Barangay 12</fullName>
            </value>
            <value>
                <fullName>Barangay 13</fullName>
            </value>
            <value>
                <fullName>Barangay 13 - Matter / Kampo / Sabang</fullName>
            </value>
            <value>
                <fullName>Barangay 14</fullName>
            </value>
            <value>
                <fullName>Barangay 15</fullName>
            </value>
            <value>
                <fullName>Bonghon</fullName>
            </value>
            <value>
                <fullName>Dapdap</fullName>
            </value>
            <value>
                <fullName>Japitan</fullName>
            </value>
            <value>
                <fullName>Malaintos</fullName>
            </value>
            <value>
                <fullName>Malobago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Fee_Setting__mdt/fields/Delivery_Fee__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Fee__c</fullName>
    <label>Delivery Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_of_Payment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TECH_LastName__c.field-meta.xml
<CustomField>
    <fullName>TECH_LastName__c</fullName>
    <label>TECH LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/Lead_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Lead Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lead Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Line_Item__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Special_Notes__c.field-meta.xml
<CustomField>
    <fullName>Special_Notes__c</fullName>
    <label>Special Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>TECH_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_MainProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_PricebookEntry__c.field-meta.xml
<CustomField>
    <fullName>TECH_PricebookEntry__c</fullName>
    <label>TECH_PricebookEntry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Complete_Address__c.field-meta.xml
<CustomField>
    <fullName>Complete_Address__c</fullName>
    <label>Complete Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_of_Payment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Time__c.field-meta.xml
<CustomField>
    <fullName>Order_Time__c</fullName>
    <label>Order Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/POS_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>POS_Display_Name__c</fullName>
    <inlineHelpText>Name use to display in the Receipt and POS</inlineHelpText>
    <label>POS Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Special_Notes__c.field-meta.xml
<CustomField>
    <fullName>Special_Notes__c</fullName>
    <label>Special Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TECH_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>TECH_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_MainProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Resto_Site_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Resto_Site_Display_Name__c</fullName>
    <label>Resto Site Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/Product_Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Product Stock Level</label>
    <nameField>
        <displayFormat>SLP{0000}</displayFormat>
        <label>Stock Level Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <formula>Stock_Level__r.Available_to_Sell__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available to Sell</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <referenceTo>Stock_Level__c</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Units</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Stock Level</label>
    <nameField>
        <displayFormat>SL{0000}</displayFormat>
        <label>Stock Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available to Sell</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Change_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Change_Quantity__c</fullName>
    <label>Change Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock Levels</relationshipLabel>
    <relationshipName>Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Barangays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barangay 1</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 2</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 2 - Salak</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 3</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 4</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 5</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 6</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 7</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 8</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 9</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 10</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 11</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 12</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 13</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 13 - Matter / Kampo / Sabang</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 14</fullName>
    </customValue>
    <customValue>
        <fullName>Barangay 15</fullName>
    </customValue>
    <customValue>
        <fullName>Bonghon</fullName>
    </customValue>
    <customValue>
        <fullName>Dapdap</fullName>
    </customValue>
    <customValue>
        <fullName>Japitan</fullName>
    </customValue>
    <customValue>
        <fullName>Malaintos</fullName>
    </customValue>
    <customValue>
        <fullName>Malobago</fullName>
    </customValue>
    <masterLabel>Barangays</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Mode_of_Payment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cash</fullName>
        <default>true</default>
        <label>Cash</label>
    </customValue>
    <customValue>
        <fullName>Gcash</fullName>
    </customValue>
    <customValue>
        <fullName>COD</fullName>
    </customValue>
    <customValue>
        <fullName>COP</fullName>
    </customValue>
    <masterLabel>Mode of Payment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Municipalities_Cities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dolores</fullName>
    </customValue>
    <masterLabel>Municipalities / Cities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FGCustomerDetailsController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/ 
public without sharing class FGCustomerDetailsController {
    
    @AuraEnabled
    public static List<String> getPicklistValues(String objectName, String fieldName) {
        List<String> options = new List<String>();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        
        List<Schema.PicklistEntry> values = fieldMap.get(fieldName).getDescribe().getPickListValues();
        
        for (Schema.PicklistEntry entry : values) {
            options.add(entry.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static Lead getLead(String leadId){
        
        Lead l = [SELECT Id, FirstName, LastName, MobilePhone, Municipality_City__c, Barangay_Sitio__c, Complete_Address__c, TECH_LastName__c, Company FROM Lead WHERE Id =: leadId];
        
        return l;
    }
    
    @AuraEnabled
    public static List<Lead_Line_Item__c> getLeadItems(String leadId){
        
        List<Lead_Line_Item__c> lineItems = [SELECT Id, TECH_MainProduct__c, Product__c, Product__r.Name,Product__r.Product_Image_Url__c, Quantity__c, Total_Price__c, Product__r.Resto_Site_Display_Name__c 
                                             FROM Lead_Line_Item__c WHERE Lead__c =: leadId ORDER BY TECH_MainProduct__c DESC];
        
        return lineItems; 
    }
    
    @AuraEnabled
    public static Lead updateLead(Lead lead){
        
        lead.LastName = lead.TECH_LastName__c;
        lead.LeadSource = 'Web';
        lead.Mode_of_Payment__c = 'COD';
        lead.Municipality_City__c = 'Dolores';
        update lead;
        
        return lead; 
    }
    
    @AuraEnabled
    public static Lead_Line_Item__c addDelivery(String leadId, String barangay){
        
        Map<String, Delivery_Fee_Setting__mdt> feeSettingsMap = Delivery_Fee_Setting__mdt.getAll();
        List<Delivery_Fee_Setting__mdt> feeSettingsList = feeSettingsMap.values();
        Map<String, Decimal> deliveryFeeMap = new Map<String, Decimal>();
        
        for(Delivery_Fee_Setting__mdt df : feeSettingsList){
            deliveryFeeMap.put(df.Barangay_Sitio__c, df.Delivery_Fee__c);
        }
        
        //Check if there is already a delivery line item
         Lead_Line_Item__c lineItem = new Lead_Line_Item__c();
        if(deliveryFeeMap.containsKey(barangay)){
            
            
           
            List<Lead_Line_Item__c> deliveryItem = [SELECT Id, Unit_Price__c FROM Lead_Line_Item__c WHERE Lead__c =: leadId AND Product__r.Name = 'Delivery Fee' LIMIT 1];
            if(deliveryItem.size() > 0){
                lineItem = deliveryItem[0];
                lineItem.Unit_Price__c = deliveryFeeMap.get(barangay);
            }else{
                PriceBookEntry deliveryProd = [SELECT Id, Product2Id, UnitPrice FROM PriceBookEntry WHERE Product2.Name = 'Delivery Fee' LIMIT 1];
                
                lineItem.Product__c = deliveryProd.Product2Id;
                lineItem.Unit_Price__c = deliveryFeeMap.get(barangay);
                lineItem.Quantity__c = 1;
                lineItem.TECH_PricebookEntry__c = deliveryProd.Id;
                lineItem.Lead__c = leadId;
            }
            
            upsert lineItem;
        }
        
        
        //update Lead
        Lead l = [SELECT Id, Barangay_Sitio__c FROM Lead WHERE Id=: leadId];
        l.Barangay_Sitio__c = barangay;
        update l;
        
        
        system.debug('LEAD ITEM: ' + l);
        return lineItem; 
    }
    
    
    @AuraEnabled
    public static List<Stock_Level__c> checkProductsStockList(Lead lead){
        
        Map<String, Lead_Line_Item__c> leadItemMap = new Map<String, Lead_Line_Item__c>();
        for(Lead_Line_Item__c li : [SELECT Id, Product__c, TECH_MainProduct__c, Product__r.Name, Product__r.Resto_Site_Display_Name__c, Quantity__c, Total_Price__c, Unit_Price__c, Special_Notes__c, TECH_PricebookEntry__c
                                    FROM Lead_Line_Item__c WHERE Lead__c =: lead.Id AND Product__r.Track_Inventory__c = TRUE]){
                                        
                                        
                                        leadItemMap.put(li.Product__c, li);
                                        
                                        
                                        
                                    }
        
        Map<Id, Stock_Level__c> currentStockLevelMap = new Map<Id, Stock_Level__c>(); 
        for(Product_Stock_Level__c psl : [SELECT Id, Product__c, Stock_Level__c, Available_to_Sell__c, Units__c FROM Product_Stock_Level__c WHERE Product__c IN : leadItemMap.keySet()]){
            
            
            if(leadItemMap.containsKey(psl.Product__c)){
                
                if(currentStockLevelMap.containsKey(psl.Stock_Level__c)){
                    //Current quantity + the new units sold
                    currentStockLevelMap.get(psl.Stock_Level__c).Change_Quantity__c = currentStockLevelMap.get(psl.Stock_Level__c).Change_Quantity__c + (leadItemMap.get(psl.Product__c).Quantity__c * psl.Units__c);
                }else{
                    
                    Stock_Level__c sl = new Stock_Level__c();
                    sl.Id = psl.Stock_Level__c;
                    sl.Change_Quantity__c = leadItemMap.get(psl.Product__c).Quantity__c * psl.Units__c;
                    currentStockLevelMap.put(psl.Stock_Level__c, sl);
                }
                
                
            }
            
            
            
            
        }
        
        
        //Make the change quantity negative value
        for(String slKey : currentStockLevelMap.KeySet()){
            
            if(currentStockLevelMap.containsKey(slKey)){
                currentStockLevelMap.get(slKey).Change_Quantity__c = -(currentStockLevelMap.get(slKey).Change_Quantity__c);
            }
            
        } 
        
        
        for(Product_Stock_Level__c psl : [SELECT Id, Product__c, Stock_Level__c, Stock_Level__r.Name, Available_to_Sell__c, Units__c FROM Product_Stock_Level__c 
                                          WHERE Product__c IN : leadItemMap.keySet()]){
                                              
                                              if(currentStockLevelMap.containsKey(psl.Stock_Level__c)){
                                                  //Change Quantity is in NEgative so that the stock gets minus because of flow
                                                  Decimal stockCount = psl.Available_to_Sell__c + currentStockLevelMap.get(psl.Stock_Level__c).Change_Quantity__c;
                                                  if(stockCount < 0){
                                                      
                                                      try {
                                                          Map<String, String> errorMap = new Map<String, String>{
                                                              'code' => '400',
                                                                  'message' => 'ERROR: ' + psl.Stock_Level__r.Name + ' is out of stock or not enough. Please remove it from your Cart. \n  Available stock is ' + psl.Available_to_Sell__c ,
                                                                  'severity' => 'High'
                                                                  };
                                                                      throw new AuraHandledException(JSON.serialize(errorMap));
                                                          
                                                      } catch (Exception e) {
                                                          // If it's already an AuraHandledException, rethrow it
                                                          if(e instanceof AuraHandledException) throw e;
                                                          // Otherwise, wrap the system error
                                                          throw new AuraHandledException('System Error: ' + e.getMessage());
                                                      }
                                                      
                                                  }
                                                  
                                              }
                                              
                                          }
        
        if(currentStockLevelMap.size() > 0){
           
        }
        
         return currentStockLevelMap.values();
    }
    
    
    @AuraEnabled
    public static Lead placeOrder(Lead lead){
        
        //Check stocks and return an error if no stocks found
        List<Stock_Level__c> productsStockMap =  checkProductsStockList(lead);
        
        List<Account> acc = [SELECT Id FROM Account WHERE Name =: lead.Company LIMIT 1];
        if(acc.size() > 0){
            
            List<Contact> contacts = [SELECT Id, FirstName, LastName, MobilePhone, Complete_Address__c, Municipality_City__c, Barangay_Sitio__c FROM Contact WHERE MobilePhone =: lead.MobilePhone];
            Contact con = new Contact();
            if(contacts.size() > 0){
                con = contacts[0];
                con.FirstName = lead.FirstName;
                con.LastName = lead.LastName;
                con.MobilePhone = lead.MobilePhone;
                con.Complete_Address__c = lead.Complete_Address__c;
                con.Municipality_City__c = lead.Municipality_City__c;
                con.Barangay_Sitio__c = lead.Barangay_Sitio__c;
                
                update con;
            }else{
                con.FirstName = lead.FirstName;
                con.LastName = lead.LastName;
                con.MobilePhone = lead.MobilePhone;
                con.Complete_Address__c = lead.Complete_Address__c;
                con.Municipality_City__c = lead.Municipality_City__c;
                con.Barangay_Sitio__c = lead.Barangay_Sitio__c;
                con.AccountId = acc[0].Id;
                insert con;
            }
            
            
            //Create Opportunity
            Opportunity opp = new Opportunity();
            opp.Name = 'DE-';
            opp.StageName = 'Pending Review';
            opp.CloseDate = System.today();
            opp.AccountId = acc[0].Id;
            opp.Customer__c = con.Id;
            opp.Mobile_Number__c = lead.MobilePhone;
            opp.Complete_Address__c = lead.Complete_Address__c;
            opp.Mode_of_Payment__c = lead.Mode_of_Payment__c;
            opp.Type = 'Delivery';
            opp.Lead__c = lead.Id;
            opp.Order_Time__c = system.now().time();
            insert opp;
            
            opp = [SELECT Id, Name, Opportunity_Number__c FROM Opportunity WHERE Id =: opp.Id];
            opp.Name = opp.Name + opp.Opportunity_Number__c;
            update opp; 
            
            //create opportunity contact role
            OpportunityContactRole contactRole = new OpportunityContactRole();
            contactRole.ContactId = con.Id;
            contactRole.Role = 'Online Customer';
            contactRole.IsPrimary = true;
            contactRole.OpportunityId = opp.Id;
            insert contactRole;
            
            //Create Opportunity Line Item
            List<OpportunityLineItem> opptyLineItems = new List<OpportunityLineItem>();
            for(Lead_Line_Item__c li : [SELECT Id, Product__c, TECH_MainProduct__c, Product__r.Name, Product__r.Resto_Site_Display_Name__c, Quantity__c, Total_Price__c, Unit_Price__c, Special_Notes__c, TECH_PricebookEntry__c
                                        FROM Lead_Line_Item__c WHERE Lead__c =: lead.Id ]){
                                            
                                            
                                            OpportunityLineItem oppLine = new OpportunityLineItem();
                                            oppLine.OpportunityId = opp.Id;
                                            oppLine.Product2Id = li.Product__c;
                                            oppLine.Quantity = li.Quantity__c;
                                            oppLine.UnitPrice = li.Unit_Price__c;
                                            oppLine.POS_Display_Name__c = li.Product__r.Resto_Site_Display_Name__c;
                                            oppLine.Special_Notes__c = li.Special_Notes__c;
                                            oppLine.PricebookEntryId = li.TECH_PricebookEntry__c;
                                            oppLine.TECH_MainProduct__c = li.TECH_MainProduct__c;
                                            opptyLineItems.add(oppLine);
                                            
                                            
                                        }
            
            if(opptyLineItems.size() > 0){
                insert opptyLineItems;
                system.debug('LEADId: ' + lead.Id);
                //Delete items in the cart
                List<Lead_Line_Item__c> llis = [SELECT Id FROM Lead_Line_Item__c WHERE Lead__c =: lead.Id];
                delete llis;
            }
            
        }
        
        
        
        
        
        return lead; 
    }
    
}