force-app/main/default/objects/Product_Catalog_Item__c/Product_Catalog_Item__c.object-meta.xml
<CustomObject>
    <label>Product Catalog Item</label>
    <nameField>
        <displayFormat>PCI{000000}</displayFormat>
        <label>Product Catalog Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/TECH_InStock__c.field-meta.xml
<CustomField>
    <fullName>TECH_InStock__c</fullName>
    <defaultValue>true</defaultValue>
    <label>TECH_InStock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/Product_Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Product Stock Level</label>
    <nameField>
        <displayFormat>SLP{0000}</displayFormat>
        <label>Stock Level Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Stock Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <formula>Stock_Level__r.Available_to_Sell__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available to Sell</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Stock_Level__c/fields/Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Stock_Level__c</fullName>
    <label>Stock Level</label>
    <referenceTo>Stock_Level__c</referenceTo>
    <relationshipLabel>Product Stock Levels</relationshipLabel>
    <relationshipName>Product_Stock_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Stock Level</label>
    <nameField>
        <displayFormat>SL{0000}</displayFormat>
        <label>Stock Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available to Sell</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock Levels</relationshipLabel>
    <relationshipName>Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockLevelTriggerHandler.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/  
public class StockLevelTriggerHandler extends TriggerHandler{
    
    private Map<Id, Stock_Level__c> newStockLevelMap;
    private List<Stock_Level__c> newStockLevel;
    
    public StockLevelTriggerHandler() {
        this.newStockLevelMap = (Map<Id, Stock_Level__c>) Trigger.newMap;
        this.newStockLevel = (List<Stock_Level__c>) Trigger.new;
    }
    
    public override void afterUpdate() {
        
        Set<Id> noStockProdIdsSet = new Set<Id>();
        Set<Id> inStockProdIdsSet = new Set<Id>();
        Map<Id, Stock_Level__c> stockLevelMap = new Map<Id, Stock_Level__c>(newStockLevel);
        Map<Id, Product_Catalog_Item__c> prodCatalogItemMap = new Map<Id, Product_Catalog_Item__c>();
        
        
        
        //Get the affected products.  
        for(Product_Stock_Level__c psl : [SELECT Id, Stock_Level__c, Product__c, Available_to_Sell__c 
                                          FROM Product_Stock_Level__c WHERE Stock_Level__c IN : newStockLevel]){
                                              
                                              if(stockLevelMap.containsKey(psl.Stock_Level__c)){
                                                  
                                                  if(stockLevelMap.get(psl.Stock_Level__c).Available_to_Sell__c <= 0){
                                                      noStockProdIdsSet.add(psl.Product__c);
                                                      
                                                  }else{
                                                      inStockProdIdsSet.add(psl.Product__c);
                                                  }
                                                  
                                              }
                                          }
        
        //Search all Product Catalog Item where to update 
        List<Product_Catalog_Item__c> PCIToUpdate = new List<Product_Catalog_Item__c>();
		

        //get all No Stock Products        
        for(Product_Catalog_Item__c pci : [SELECT Id, Product__c, TECH_InStock__c FROM Product_Catalog_Item__c WHERE Product__c IN : noStockProdIdsSet]){
            
            pci.TECH_InStock__c = false;
            PCIToUpdate.add(pci);   
        }
        
        //get all In Stock Products   
        
        for(Product_Catalog_Item__c pci : [SELECT Id, Product__c, TECH_InStock__c FROM Product_Catalog_Item__c WHERE Product__c IN : inStockProdIdsSet]){
            
            pci.TECH_InStock__c = true;
            PCIToUpdate.add(pci);   
        }
         
        if(PCIToUpdate.size() > 0){
            update PCIToUpdate;
        }
        
    }
    
}