force-app/main/default/objects/Lead/fields/IP_Address__c.field-meta.xml
<CustomField>
    <fullName>IP_Address__c</fullName>
    <label>IP Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/Lead_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Lead Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lead Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Line_Item__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lead Line Items</relationshipLabel>
    <relationshipName>Lead_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Special_Notes__c.field-meta.xml
<CustomField>
    <fullName>Special_Notes__c</fullName>
    <label>Special Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>TECH_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_MainProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/TECH_PricebookEntry__c.field-meta.xml
<CustomField>
    <fullName>TECH_PricebookEntry__c</fullName>
    <label>TECH_PricebookEntry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Catalog__c/Product_Catalog__c.object-meta.xml
<CustomObject>
    <label>Product Catalog</label>
    <nameField>
        <label>Product Catalog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalog_Item__c/Product_Catalog_Item__c.object-meta.xml
<CustomObject>
    <label>Product Catalog Item</label>
    <nameField>
        <displayFormat>PCI{000000}</displayFormat>
        <label>Product Catalog Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alacarte</fullName>
            </value>
            <value>
                <fullName>Meal - with Rice</fullName>
            </value>
            <value>
                <fullName>Meal - Unli Rice</fullName>
            </value>
            <value>
                <fullName>Meal - with Rice &amp; Drink</fullName>
            </value>
            <value>
                <fullName>Bilao / Family Bundle</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Veggies</fullName>
            </value>
            <value>
                <fullName>Inasal</fullName>
            </value>
            <value>
                <fullName>BBQ/Grill/Lechon</fullName>
            </value>
            <value>
                <fullName>Add ons</fullName>
            </value>
            <value>
                <fullName>Dessert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Display_in_Website__c.field-meta.xml
<CustomField>
    <fullName>Display_in_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in Website</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Product_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalog__c</fullName>
    <label>Product Catalog</label>
    <referenceTo>Product_Catalog__c</referenceTo>
    <relationshipName>Product_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/Row_Priority__c.field-meta.xml
<CustomField>
    <fullName>Row_Priority__c</fullName>
    <label>Row Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/TECH_InStock__c.field-meta.xml
<CustomField>
    <fullName>TECH_InStock__c</fullName>
    <defaultValue>true</defaultValue>
    <label>TECH_InStock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/TECH_PriceBookEntryId__c.field-meta.xml
<CustomField>
    <fullName>TECH_PriceBookEntryId__c</fullName>
    <label>TECH_PriceBookEntryId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Catalog_Item__c/fields/TECH_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>TECH_Unit_Price__c</fullName>
    <label>TECH_Unit_Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resto_Site_Setting__mdt/Resto_Site_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Resto Site Setting</label>
    <pluralLabel>Resto Site Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Resto_Site_Setting__mdt/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <label>Catalog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/Stock_Level__c.object-meta.xml
<CustomObject>
    <label>Stock Level</label>
    <nameField>
        <displayFormat>SL{0000}</displayFormat>
        <label>Stock Level Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Level__c/fields/Available_to_Sell__c.field-meta.xml
<CustomField>
    <fullName>Available_to_Sell__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available to Sell</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Level__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Stock Levels</relationshipLabel>
    <relationshipName>Stock_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FGCustomizeOrderController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/  
public without sharing class FGCustomizeOrderController {
    
    
    @auraEnabled
    public static Resto_Site_Setting__mdt getSiteSettings(String settingName){
        Resto_Site_Setting__mdt posSettings = new Resto_Site_Setting__mdt();
        if(settingName != ''){
            return Resto_Site_Setting__mdt.getInstance(settingName);
        }else{
            return null;
        }
        
    }
    
    
    @AuraEnabled
    public static PriceBookEntry getProductDetail(String recordId){
        
        
        return [SELECT Id, UnitPrice, Product2Id, Product2.Name, Product2.Product_Image_Url__c, Product2.Description, Product2.Family
                FROM PriceBookEntry WHERE Product2Id =: recordId];
        
        
    }
    
    
    @AuraEnabled
    public static List<Product_Catalog_Item__c> getProductsByCategory(String category){
        
        Resto_Site_Setting__mdt fGrillSettings = getSiteSettings('Farm_Grill_Settings');
        
        Set<Id> prodIds = new Set<Id>(); 
        Set<Id> trackedProdIds = new Set<Id>(); 
        Map<Id, PricebookEntry> pbEntryMap = new Map<Id, PricebookEntry>();
        List<PriceBookEntry> productsToDisplay = new List<PriceBookEntry>();
        
        List<Product_Catalog_Item__c> catalogItems = [SELECT Id, Product__c, Product__r.Name, Product__r.Track_Inventory__c, Row_Priority__c, Category__c, TECH_InStock__c FROM Product_Catalog_Item__c 
                                                      WHERE Category__c =: category AND Product_Catalog__r.Name =: fGrillSettings.Catalog__c AND Display_in_Website__c = true
                                                      ORDER BY Row_Priority__c ASC];
        for(Product_Catalog_Item__c ci : catalogItems){
            prodIds.add(ci.Product__c);
            
            if(ci.Product__r.Track_Inventory__c){
                trackedProdIds.add(ci.Product__c);
            }
        }
        
        for(PriceBookEntry pbEntry : [SELECT Id, UnitPrice, Product2Id, Product2.Name, Product2.Product_Image_Url__c, Product2.Description, Product2.Family
                                      FROM PriceBookEntry WHERE Product2Id IN : prodIds]){
                                          
                                          pbEntryMap.put(pbEntry.Product2Id, pbEntry);
                                          
                                      }
        
        
        //Check stock level
        Map<Id,Stock_Level__c> stockLevelProdMap = new Map<Id,Stock_Level__c>();
        for(Stock_Level__c sl : [SELECT Id, Product__c, Available_to_Sell__c FROM Stock_Level__c WHERE Product__c IN : trackedProdIds]){
            stockLevelProdMap.put(sl.Product__c, sl);
        }
        
        
        for(Product_Catalog_Item__c ci : catalogItems){
            
            if(pbEntryMap.containsKey(ci.Product__c)){
                //productsToDisplay.add(pbEntryMap.get(ci.Product__c));
                ci.TECH_PriceBookEntryId__c = pbEntryMap.get(ci.Product__c).Id;
                ci.TECH_Unit_Price__c = pbEntryMap.get(ci.Product__c).UnitPrice;
            }
            
            //Check Stock if track inventory is true then check stock, otherwise true
            if(stockLevelProdMap.containsKey(ci.Product__c)){
                if(stockLevelProdMap.get(ci.Product__c).Available_to_Sell__c > 0){
                    ci.TECH_InStock__c = true;
                }
            }else{
                ci.TECH_InStock__c = true;  //always true if track inventory is false on product level
            }
            
            
        }
         
        return catalogItems;
        
        
    }
    
    
    @AuraEnabled
    public static Lead createLead(PriceBookEntry product, Integer quantity, List<String> beverages, List<String> desserts, String notes, String ipAddress){
        List<String> addOns = new List<String>();
        
        Lead l = new Lead();
        l.LastName = 'Online Customer';
        l.Company = 'Farm Grill';
        l.IP_Address__c = ipAddress;
        
        insert l;
        
        //Create Main Order
        List<Lead_Line_Item__c> leadItems = new List<Lead_Line_Item__c>();
        Lead_Line_Item__c item = new Lead_Line_Item__c();
        item.Lead__c = l.Id;
        item.Product__c = product.Product2Id;
        item.Unit_Price__c = product.UnitPrice;
        item.TECH_PricebookEntry__c = product.Id;
        item.Quantity__c = quantity;
        item.Special_Notes__c = notes;
        item.TECH_MainProduct__c = true;
        leadItems.add(item);
        
        
        if(beverages.size() > 0){
            addOns.addAll(beverages);
        }
        
        if(desserts.size() > 0){
            addOns.addAll(desserts);
        }
        
        if(addOns.size() > 0){
            for(PriceBookEntry pbItem : [SELECT Id, UnitPrice, Product2Id FROM PriceBookEntry WHERE Id IN : addOns AND PriceBook2.Name = 'Standard Price Book']){
                
                Lead_Line_Item__c addOn = new Lead_Line_Item__c();
                addOn.Lead__c = l.Id;
                addOn.Product__c = pbItem.Product2Id;
                addOn.Unit_Price__c = pbItem.UnitPrice;
                addOn.TECH_PricebookEntry__c = pbItem.Id;
                addOn.Quantity__c = quantity;
                leadItems.add(addOn);
                
            }
            
            if(leadItems.size() > 0){
                insert leadItems;
                
            }
        }
        
        
        
        return l;
        
        
    }
    
    @AuraEnabled
    public static String updateLead(String leadId, PriceBookEntry product, Integer quantity, List<String> beverages, List<String> desserts, String notes, String ipAddress){
        
        List<String> addOns = new List<String>();
        List<Lead_Line_Item__c> leadItems = new List<Lead_Line_Item__c>();
        
        if(beverages.size() > 0){
            addOns.addAll(beverages);
        }
        
        if(desserts.size() > 0){
            addOns.addAll(desserts);
        }
        
        
        
        Map<Id, Lead_Line_Item__c> leadItemsMap = new Map<Id, Lead_Line_Item__c>();
        
        
        for(Lead_Line_Item__c li : [SELECT Id, Quantity__c, Product__c FROM Lead_Line_Item__c WHERE Lead__c =: leadId]){
            leadItemsMap.put(li.Product__c, li);
        }
        
        
        //Create Main Order
        Lead_Line_Item__c mainItem = new Lead_Line_Item__c();
        if(leadItemsMap.containsKey(product.Product2Id)){
            //If found update the main product
            mainItem = leadItemsMap.get(product.Product2Id);
            mainItem.Quantity__c = leadItemsMap.get(product.Product2Id).Quantity__c + quantity;
            mainItem.TECH_MainProduct__c = true;
            leadItems.add(mainItem);
            
        }else{
            //create a new one
            
            mainItem.Lead__c = leadId;
            mainItem.Product__c = product.Product2Id;
            mainItem.Unit_Price__c = product.UnitPrice;
            mainItem.TECH_PricebookEntry__c = product.Id;
            mainItem.Quantity__c = quantity;
            mainItem.Special_Notes__c = notes;
            mainItem.TECH_MainProduct__c = true;
            leadItems.add(mainItem);
        }
        
        if(addOns.size() > 0){
            
            
            for(PriceBookEntry pbItem : [SELECT Id, UnitPrice, Product2Id FROM PriceBookEntry WHERE Id IN : addOns AND PriceBook2.Name = 'Standard Price Book']){
                
                Lead_Line_Item__c addOn = new Lead_Line_Item__c(); 
                
                if(leadItemsMap.containsKey(pbItem.Product2Id)){
                    addOn = leadItemsMap.get(pbItem.Product2Id);
                    addOn.Quantity__c = addOn.Quantity__c + quantity;
                    leadItems.add(addOn);
                    
                }else{
                    
                    addOn.Lead__c = leadId;
                    addOn.Product__c = pbItem.Product2Id;
                    addOn.Unit_Price__c = pbItem.UnitPrice;
                    addOn.TECH_PricebookEntry__c = pbItem.Id;
                    addOn.Quantity__c = quantity;
                    leadItems.add(addOn);
                    
                }
                
                
                
            }
            
            
            

            
            
            
            
            
        }
        
        if(leadItems.size() > 0){
            upsert leadItems;
            
        }
        
        return leadId;
        
        
    }
    
}