force-app/main/default/objects/Opportunity/fields/Cash_Tendered__c.field-meta.xml
<CustomField>
    <fullName>Cash_Tendered__c</fullName>
    <label>Cash Tendered</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <formula>IF( Cash_Tendered__c  != 0 , Cash_Tendered__c - Amount, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Queue_Number__c.field-meta.xml
<CustomField>
    <fullName>Queue_Number__c</fullName>
    <label>Queue Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/POSCustomerReceiptController.cls
/*
@Author: Chad Lazarra (shagilazarra@gmail.com)
@Date:
@Desc:
@History

*/ 
public without sharing class POSCustomerReceiptController {
    
    public class ReceiptData{
        @auraEnabled
        public Opportunity oppty;
        @auraEnabled
        public List<OpportunityLineItem> opptyLines;
    }
    
    @auraEnabled
    public static ReceiptData getReceiptData(String recordId){
        system.debug('#' + recordId);
        ReceiptData receipt = new ReceiptData();
        receipt.oppty = [SELECT Id, Queue_Number__c, Amount, Cash_Tendered__c, Change__c FROM Opportunity WHERE Id =: recordId];
        receipt.opptyLines = [SELECT Id, Product2.Name, Quantity, TotalPrice FROM OpportunityLineItem WHERE OpportunityId =: recordId];
        
        return receipt;        
    }
    
  

}