force-app/main/default/objects/Contact/fields/PWD_Id__c.field-meta.xml
<CustomField>
    <fullName>PWD_Id__c</fullName>
    <label>PWD Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sr_Citizen_Id__c.field-meta.xml
<CustomField>
    <fullName>Sr_Citizen_Id__c</fullName>
    <label>Sr Citizen Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POS_Setting__mdt/POS_Setting__mdt.object-meta.xml
<CustomObject>
    <label>POS Setting</label>
    <pluralLabel>POS Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/POS_Setting__mdt/fields/Discount_Passcode__c.field-meta.xml
<CustomField>
    <fullName>Discount_Passcode__c</fullName>
    <label>Discount Passcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/POSApprovalModalController.cls
public without sharing class POSApprovalModalController {
    
    @AuraEnabled
    public static POS_Setting__mdt getPosSettings(){
        
        POS_Setting__mdt settings = [SELECT Id, DeveloperName, Discount_Passcode__c, Account_Name__c FROM POS_Setting__mdt WHERE DeveloperName = 'Farm_Grill_Settings' LIMIT 1];
        
        
        return settings;
    }
    
    @AuraEnabled
    public static Contact createSrPwdRecord(Contact con){
        List<Contact> customers = [SELECT Id FROM Contact WHERE LastName =: con.LastName AND Sr_Citizen_Id__c =: con.Sr_Citizen_Id__c AND PWD_Id__c =: con.PWD_Id__c LIMIT 1];
        List<Account> farmGrillAcc = [SELECT Id FROM Account WHERE Name = 'Farm Grill'];
        con.AccountId = farmGrillAcc[0].Id;
        
        if(customers.size() > 0){
            con.Id = customers[0].Id;
            update con;
        }else{
            insert con;
        }
        
        
        return con;
    }
    
    
}